require("babel-runtime/regenerator")
require("babel-register")
require("webpack-hot-middleware/client?reload=true")
require("./styles.scss")
require("./images/link.jpg")
require("./index.html")
require("./app")
